services:
  backstage:
    build:
      context: .
    ports:
      - '${PORT}:${PORT}'
    env_file:
      - .env
    environment:
      NODE_ENV: ${NODE_ENV}
      PORT: ${PORT}
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      - db
    networks:
      - backstage_network

  db:
    image: postgres:15
    container_name: backstage_db
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backstage_network

volumes:
  postgres_data:

networks:
  backstage_network:
    driver: bridge
