services:
  backstage:
    image: backstage # Nome da imagem do Backstage gerada pelo Dockerfile
    build:
      context: . # Diretório onde está o Dockerfile
    ports:
      - '3000:3000' # Porta externa mapeada para o serviço
    environment:
      NODE_ENV: production
      PORT: 3000
      DATABASE_URL: postgres://backstage_user:password@db:5432/backstage # Configuração do banco de dados
    depends_on:
      - db
    networks:
      - backstage_network

  db:
    image: postgres:15 # Versão do PostgreSQL
    container_name: backstage_db
    restart: always
    environment:
      POSTGRES_USER: backstage_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: backstage
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backstage_network

volumes:
  postgres_data:

networks:
  backstage_network:
    driver: bridge
